apiVersion: v1
kind: ConfigMap
metadata:
  name: step-ca-config
  namespace: default
  labels:
    app: step-ca
data:
  ca.json: |
    {
      "root": "/home/step/certs/root_ca.crt",
      "federatedRoots": null,
      "crt": "/home/step/certs/intermediate_ca.crt",
      "key": "/home/step/secrets/intermediate_ca_key",
      "address": ":9000",
      "insecureAddress": "",
      "dnsNames": [
        "localhost"
      ],
      "logger": {
        "format": "text"
      },
      "db": {
        "type": "badgerv2",
        "dataSource": "/home/step/db",
        "badgerFileLoadingMode": ""
      },
      "authority": {
        "enableAdmin": true
      },
      "tls": {
          "cipherSuites": [
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        ],
        "minVersion": 1.2,
        "maxVersion": 1.3,
        "renegotiation": false
      }
    }