apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: step-ca-db
  namespace: default
  labels:
    app: step-ca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
