apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-certs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  intermediate_ca.crt: |
    {{ .Values.certificates.intermediate_ca_crt | nindent 4 }}
  root_ca.crt: |
    {{ .Values.certificates.root_ca_crt | nindent 4 }}
