apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.secrets.namespace }}
  labels:
    app: {{ .Values.app }}
stringData:
  password: {{ .Values.secrets.password | quote }}
  intermediate_ca_key: |
{{ .Values.secrets.intermediate_ca_key | indent 4 }}
