replicaCount: 1
image:
  repository: step-ca
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}

securityContext: {}
service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: step-ca-config
    configMap:
      name: step-ca-config
  - name: step-ca-db
    persistentVolumeClaim:
      claimName: step-ca-db
  - name: step-ca-secrets
    secret:
      secretName: step-ca-secrets
  - name: step-ca-certs
    secret:
      secretName: step-ca-certs

volumeMounts:
  - name: step-ca-config
    mountPath: /home/step/config
    readOnly: true
  - name: step-ca-db
    mountPath: /home/step/db
  - name: step-ca-secrets
    mountPath: /home/step/secrets
    readOnly: true
  - name: step-ca-certs
    mountPath: /home/step/certs
    readOnly: true

nodeSelector: {}
tolerations: []
affinity: {}

certificates:
  intermediate_ca_crt: |
    -----BEGIN CERTIFICATE-----
    MIIBzTCCAXKgAwIBAgIQXlYEgIkZ79XoeoDLp2B3yzAKBggqhkjOPQQDAjAwMRIw
    EAYDVQQKEwlTbWFsbHN0ZXAxGjAYBgNVBAMTEVNtYWxsc3RlcCBSb290IENBMB4X
    DTI0MTIyNDE5MjYzOFoXDTM0MTIyMjE5MjYzOFowODESMBAGA1UEChMJU21hbGxz
    dGVwMSIwIAYDVQQDExlTbWFsbHN0ZXAgSW50ZXJtZWRpYXRlIENBMFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAEis4RRsxKQa9YUc2F0QZCWq4849RHXbKc5N1XDkbI
    5jqZ0zC3LRW486P9Q5+LkmobFCTr9HYBZlaAKegjdYW316NmMGQwDgYDVR0PAQH/
    BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFPKKUXpCf5kLSSGh
    EZznteiPM99TMB8GA1UdIwQYMBaAFL37owYNuawVPd+EJhCu2uTV+lIGMAoGCCqG
    SM49BAMCA0kAMEYCIQCN+hp+h4XC2LUu97KFDd/8706jJaL/2WHIiwyg8ZecnAIh
    AKhYlGDWz7UiETRdgQQTG5sMj9ZEqd5vNQQ0ZAghxSj6
    -----END CERTIFICATE-----
  root_ca_crt: |
    -----BEGIN CERTIFICATE-----
    MIIBpDCCAUqgAwIBAgIRALBpWj3/MyrHJQ+awRLCRqMwCgYIKoZIzj0EAwIwMDES
    MBAGA1UEChMJU21hbGxzdGVwMRowGAYDVQQDExFTbWFsbHN0ZXAgUm9vdCBDQTAe
    Fw0yNDEyMjQxOTI2MzdaFw0zNDEyMjIxOTI2MzdaMDAxEjAQBgNVBAoTCVNtYWxs
    c3RlcDEaMBgGA1UEAxMRU21hbGxzdGVwIFJvb3QgQ0EwWTATBgcqhkjOPQIBBggq
    hkjOPQMBBwNCAAQH/oye2WivqKIPA+sEf2+alHtKkmXU0qHNlzdX6fSEeH7d+iKH
    iPoBMI2J0vk6AGcB1T/4bcmDbYBOm06fkKO2o0UwQzAOBgNVHQ8BAf8EBAMCAQYw
    EgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUvfujBg25rBU934QmEK7a5NX6
    UgYwCgYIKoZIzj0EAwIDSAAwRQIgZfSkrE5mgx32tc3L+yATQwiJiugTeseHOMvN
    CTAYZWICIQDNC+tq4zkjrPqfGL2HgiE50T0iXrORdOoXvtFnWomHhQ==
    -----END CERTIFICATE-----

config:
  caJson: |
    {
      "root": "/home/step/certs/root_ca.crt",
      "federatedRoots": null,
      "crt": "/home/step/certs/intermediate_ca.crt",
      "key": "/home/step/secrets/intermediate_ca_key",
      "address": ":9000",
      "insecureAddress": "",
      "dnsNames": [
        "localhost"
      ],
      "logger": {
        "format": "text"
      },
      "db": {
        "type": "badgerv2",
        "dataSource": "/home/step/db",
        "badgerFileLoadingMode": ""
      },
      "authority": {
        "enableAdmin": true
      },
      "tls": {
        "cipherSuites": [
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        ],
        "minVersion": 1.2,
        "maxVersion": 1.3,
        "renegotiation": false
      }
    }

pvc:
  accessModes: ReadWriteOnce
  storage: 1Gi

secrets:
  name: step-ca-secrets
  namespace: default
  password: "y6Srt5mHd7qC7TWm76HxgoyYK6l8V81gnyCP1PU2"
  intermediate_ca_key: |
    -----BEGIN EC PRIVATE KEY-----
    Proc-Type: 4,ENCRYPTED
    DEK-Info: AES-256-CBC,306a7b6bbf1961e68b349ccc2af60f28

    MDGyKqLNk+g/8GWaoVgVur7jocX+pMwwwiuuC7z9lbqZNh20/n+e4AJGRVTi1pFh
    JecZS3PBnxgIw+NQtPnyi+TmR2wOBSrtnxuiF8jlKsCgy+nER6ffUsPyViocaToF
    Ug35xQX8/sTCtBFdfq0BWj+e5NN3eu8MaeIQHlM/Foo=
    -----END EC PRIVATE KEY-----
