apiVersion: v1
kind: Secret
metadata:
  name: step-ca-certs
  namespace: default
  labels:
    app: step-ca
stringData:
  intermediate_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBzTCCAXKgAwIBAgIQXlYEgIkZ79XoeoDLp2B3yzAKBggqhkjOPQQDAjAwMRIw
    EAYDVQQKEwlTbWFsbHN0ZXAxGjAYBgNVBAMTEVNtYWxsc3RlcCBSb290IENBMB4X
    DTI0MTIyNDE5MjYzOFoXDTM0MTIyMjE5MjYzOFowODESMBAGA1UEChMJU21hbGxz
    dGVwMSIwIAYDVQQDExlTbWFsbHN0ZXAgSW50ZXJtZWRpYXRlIENBMFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAEis4RRsxKQa9YUc2F0QZCWq4849RHXbKc5N1XDkbI
    5jqZ0zC3LRW486P9Q5+LkmobFCTr9HYBZlaAKegjdYW316NmMGQwDgYDVR0PAQH/
    BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFPKKUXpCf5kLSSGh
    EZznteiPM99TMB8GA1UdIwQYMBaAFL37owYNuawVPd+EJhCu2uTV+lIGMAoGCCqG
    SM49BAMCA0kAMEYCIQCN+hp+h4XC2LUu97KFDd/8706jJaL/2WHIiwyg8ZecnAIh
    AKhYlGDWz7UiETRdgQQTG5sMj9ZEqd5vNQQ0ZAghxSj6
    -----END CERTIFICATE-----
  root_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBpDCCAUqgAwIBAgIRALBpWj3/MyrHJQ+awRLCRqMwCgYIKoZIzj0EAwIwMDES
    MBAGA1UEChMJU21hbGxzdGVwMRowGAYDVQQDExFTbWFsbHN0ZXAgUm9vdCBDQTAe
    Fw0yNDEyMjQxOTI2MzdaFw0zNDEyMjIxOTI2MzdaMDAxEjAQBgNVBAoTCVNtYWxs
    c3RlcDEaMBgGA1UEAxMRU21hbGxzdGVwIFJvb3QgQ0EwWTATBgcqhkjOPQIBBggq
    hkjOPQMBBwNCAAQH/oye2WivqKIPA+sEf2+alHtKkmXU0qHNlzdX6fSEeH7d+iKH
    iPoBMI2J0vk6AGcB1T/4bcmDbYBOm06fkKO2o0UwQzAOBgNVHQ8BAf8EBAMCAQYw
    EgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUvfujBg25rBU934QmEK7a5NX6
    UgYwCgYIKoZIzj0EAwIDSAAwRQIgZfSkrE5mgx32tc3L+yATQwiJiugTeseHOMvN
    CTAYZWICIQDNC+tq4zkjrPqfGL2HgiE50T0iXrORdOoXvtFnWomHhQ==
    -----END CERTIFICATE-----