apiVersion: v1
kind: Secret
metadata:
  name: step-ca-secrets
  namespace: default
  labels:
    app: step-ca
stringData:
  password: "y6Srt5mHd7qC7TWm76HxgoyYK6l8V81gnyCP1PU2"
  intermediate_ca_key: |
    -----BEGIN EC PRIVATE KEY-----
    Proc-Type: 4,ENCRYPTED
    DEK-Info: AES-256-CBC,306a7b6bbf1961e68b349ccc2af60f28

    MDGyKqLNk+g/8GWaoVgVur7jocX+pMwwwiuuC7z9lbqZNh20/n+e4AJGRVTi1pFh
    JecZS3PBnxgIw+NQtPnyi+TmR2wOBSrtnxuiF8jlKsCgy+nER6ffUsPyViocaToF
    Ug35xQX8/sTCtBFdfq0BWj+e5NN3eu8MaeIQHlM/Foo=
    -----END EC PRIVATE KEY-----